version: '3'
services:
  incrementserver1:
    build:  
      context: ./DisysExam
      dockerfile: Dockerfile
      args:
        APPTYPE: server
        PORT: 8080
    env_file:
      - server.env
      - .env
    environment:
      - ID=1
    ports:
      - 8080:8080
  incrementserver2:
    build:  
      context: ./DisysExam
      dockerfile: Dockerfile
      args:
        APPTYPE: server
        PORT: 8081
    env_file:
      - server.env
      - .env
    environment:
      - ID=2
    ports:
      - 8081:8081
  incrementserver3:
    build:  
      context: ./DisysExam
      dockerfile: Dockerfile
      args:
        APPTYPE: server
        PORT: 8082
    env_file:
      - server.env
      - .env
    environment:
      - ID=3
    ports:
      - 8082:8082
  frontend:
    build:
      context: ./DisysExam
      dockerfile: Dockerfile
      args:
        APPTYPE: frontend
        PORT: 8000
    env_file:
      - frontend.env
      - .env
    ports:
      - 8000:8000
      - 8001:8001
